#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG="/usr/bin/acfix-watch"

start_service() {
    procd_open_instance
    procd_set_param command "$PROG"
    # respawn: 最小间隔 最大间隔 最大重启次数(0=不限)
    procd_set_param respawn 5 60 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
